### ISSUE TITLE
Mobile Improvement : Disable smart Zoom

### ISSUE THREAD

**Issue by karlm89** [Humans-vs-AI/humans-vs-ai#43]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by luisrondow** [comment]
Can you assign me?

**Comment by karlm89** [comment]
@luisrondow your fix didn't work.

**Comment by luisrondow** [comment]
@karlm89 What specifically is to be fixed? for me it was to disable zooming on the mobile version

**Comment by karlm89** [comment]
I figured it out... It need an npm run build done @luisrondow

**Comment by luisrondow** [comment]
No problem! I'm grateful to contribute.

See ya
